# Configuration file for golangci-lint
# For more options, see https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  disable:
    - forbidigo  # forbids identifiers matched by reg exps
    - testpackage  # too opinionated about test package naming
    - wrapcheck  # requires wrapping all errors, too strict for existing code
    - wsl  # deprecated, use wsl_v5 if needed
    - cyclop  # cyclomatic complexity - too strict for existing code
    - revive  # too many opinionated rules
    - unused  # flags code that may be used in future
    - errcheck  # too many unchecked errors in existing code
    - gocritic  # too opinionated
    - prealloc  # micro-optimization
    - perfsprint  # micro-optimization
    - noctx  # too strict about context usage
    - gosec  # security scanner - creates many false positives
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - fatcontext
    - gomoddirectives
    - gomodguard
    - govet
    - iface
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - wastedassign
  settings:
    staticcheck:
      checks: ["all"]
    testifylint:
      enable-all: false
